require: rubocop-rails

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - "db/seeds.rb"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "lib/scrapers/*"

Rails/FilePath:
  Enabled: true
  Exclude:
    - "config/environments/development.rb"

Rails/Output:
  Enabled: true
  Exclude:
    - "db/seeds.rb"
    - "lib/scrapers/*"

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
